In [11]:
# prompt: 1. Learn how to read CSV files and manipulate
# data frames using Pandas.
# 2. Perform simple data cleaning tasks such as
# handling missing values and removing
# duplicates.
# 3. Practice basic data manipulation operations
# like filtering, sorting, and grouping data.

import pandas as pd

# 1. Read CSV and create a DataFrame
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
print(df)

# 2. Handle missing values
df.fillna(df.mean(), inplace=True)
print(df)

# Remove rows with any missing values
df.dropna(inplace=True)
print(df)

# Remove duplicate rows
df.drop_duplicates(inplace=True)
print(df)

# 3. Data manipulation
# Filter data
filtered_df = df[df['median_income'] > 10]
print(filtered_df)

# Sort data
sorted_df = df.sort_values('median_income')
print(sorted_df)

# Group data
grouped_df = df.groupby('median_income').mean()
print(grouped_df)

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0
1       -118.30     34.26                43.0       1510.0           310.0
2       -117.81     33.78                27.0       3589.0           507.0
3       -118.36     33.82                28.0         67.0            15.0
4       -119.67     36.33                19.0       1241.0           244.0
...         ...       ...                 ...          ...             ...
2995    -119.86     34.42                23.0       1450.0           642.0
2996    -118.14     34.06                27.0       5257.0          1082.0
2997    -119.70     36.30                10.0        956.0           201.0
2998    -117.12     34.10                40.0         96.0            14.0
2999    -119.63     34.42                42.0       1765.0           263.0

      population  households  median_income  median_house_value
0         1537.0       606.0         6.6085            344700.0
1          809.0       277.0         3.5990            176500.0
2         1484.0       495.0         5.7934            270500.0
3           49.0        11.0         6.1359            330000.0
4          850.0       237.0         2.9375             81700.0
...          ...         ...            ...                 ...
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0
2999       753.0       260.0         8.5608            500001.0

[3000 rows x 9 columns]
      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0
1       -118.30     34.26                43.0       1510.0           310.0
2       -117.81     33.78                27.0       3589.0           507.0
3       -118.36     33.82                28.0         67.0            15.0
4       -119.67     36.33                19.0       1241.0           244.0
...         ...       ...                 ...          ...             ...
2995    -119.86     34.42                23.0       1450.0           642.0
2996    -118.14     34.06                27.0       5257.0          1082.0
2997    -119.70     36.30                10.0        956.0           201.0
2998    -117.12     34.10                40.0         96.0            14.0
2999    -119.63     34.42                42.0       1765.0           263.0

      population  households  median_income  median_house_value
0         1537.0       606.0         6.6085            344700.0
1          809.0       277.0         3.5990            176500.0
2         1484.0       495.0         5.7934            270500.0
3           49.0        11.0         6.1359            330000.0
4          850.0       237.0         2.9375             81700.0
...          ...         ...            ...                 ...
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0
2999       753.0       260.0         8.5608            500001.0

[3000 rows x 9 columns]
      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0
1       -118.30     34.26                43.0       1510.0           310.0
2       -117.81     33.78                27.0       3589.0           507.0
3       -118.36     33.82                28.0         67.0            15.0
4       -119.67     36.33                19.0       1241.0           244.0
...         ...       ...                 ...          ...             ...
2995    -119.86     34.42                23.0       1450.0           642.0
2996    -118.14     34.06                27.0       5257.0          1082.0
2997    -119.70     36.30                10.0        956.0           201.0
2998    -117.12     34.10                40.0         96.0            14.0
2999    -119.63     34.42                42.0       1765.0           263.0

      population  households  median_income  median_house_value
0         1537.0       606.0         6.6085            344700.0
1          809.0       277.0         3.5990            176500.0
2         1484.0       495.0         5.7934            270500.0
3           49.0        11.0         6.1359            330000.0
4          850.0       237.0         2.9375             81700.0
...          ...         ...            ...                 ...
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0
2999       753.0       260.0         8.5608            500001.0

[3000 rows x 9 columns]
      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0
1       -118.30     34.26                43.0       1510.0           310.0
2       -117.81     33.78                27.0       3589.0           507.0
3       -118.36     33.82                28.0         67.0            15.0
4       -119.67     36.33                19.0       1241.0           244.0
...         ...       ...                 ...          ...             ...
2995    -119.86     34.42                23.0       1450.0           642.0
2996    -118.14     34.06                27.0       5257.0          1082.0
2997    -119.70     36.30                10.0        956.0           201.0
2998    -117.12     34.10                40.0         96.0            14.0
2999    -119.63     34.42                42.0       1765.0           263.0

      population  households  median_income  median_house_value
0         1537.0       606.0         6.6085            344700.0
1          809.0       277.0         3.5990            176500.0
2         1484.0       495.0         5.7934            270500.0
3           49.0        11.0         6.1359            330000.0
4          850.0       237.0         2.9375             81700.0
...          ...         ...            ...                 ...
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0
2999       753.0       260.0         8.5608            500001.0

[3000 rows x 9 columns]
      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
42      -118.06     34.15                37.0       1980.0           226.0
117     -122.07     37.34                30.0       1851.0           238.0
118     -117.18     33.02                15.0       3540.0           453.0
124     -117.81     33.84                17.0       4343.0           515.0
135     -122.34     37.56                39.0       3562.0           391.0
161     -117.85     33.62                13.0       5192.0           658.0
389     -121.88     37.46                 5.0       1819.0           245.0
474     -122.15     37.41                15.0       2577.0           360.0
481     -118.42     34.12                27.0       2089.0           303.0
502     -117.25     32.83                17.0       2075.0           262.0
506     -122.13     37.37                30.0       2139.0           260.0
531     -117.81     33.82                22.0       2898.0           335.0
686     -122.00     37.86                18.0       8953.0          1074.0
710     -122.12     37.37                37.0       1446.0           181.0
747     -118.39     33.79                30.0       4402.0           563.0
863     -117.69     33.58                 8.0       2887.0           351.0
894     -122.39     37.74                52.0        126.0            24.0
997     -119.50     34.35                39.0        308.0            38.0
1050    -121.96     37.74                 2.0        200.0            20.0
1080    -122.02     37.01                20.0       1005.0           138.0
1192    -122.45     37.79                52.0       1457.0           215.0
1222    -117.81     33.83                 8.0       7326.0           884.0
1263    -118.28     34.12                50.0       2384.0           312.0
1329    -118.12     33.77                10.0       7264.0          1137.0
1383    -118.37     34.10                37.0        407.0            67.0
1475    -118.42     34.09                40.0       3552.0           392.0
1561    -122.06     37.27                16.0       1612.0           221.0
1600    -118.10     34.13                47.0       2234.0           276.0
1865    -122.28     37.90                52.0       2003.0           250.0
1880    -121.89     37.46                 5.0       1519.0           186.0
1954    -122.47     37.87                36.0       4471.0           618.0
2004    -118.47     34.10                32.0       8041.0          1141.0
2050    -118.44     34.15                44.0       1778.0           251.0
2053    -122.25     37.45                34.0       2999.0           365.0
2199    -118.20     34.19                38.0       2176.0           266.0
2243    -122.03     37.27                25.0       4460.0           553.0
2350    -118.54     34.15                26.0      10111.0          1295.0
2384    -118.33     34.07                52.0       1482.0           171.0
2556    -118.46     34.07                49.0       2418.0           301.0
2583    -118.41     34.09                37.0       2716.0           302.0

      population  households  median_income  median_house_value
42         697.0       226.0        15.0001            500001.0
117        631.0       236.0        10.1007            500001.0
118       1364.0       425.0        13.6623            500001.0
124       1605.0       484.0        10.5981            460100.0
135       1139.0       391.0        12.6417            500001.0
161       1865.0       662.0        15.0001            500001.0
389        802.0       228.0        10.9722            500001.0
474        979.0       364.0        10.4760            500001.0
481        654.0       270.0        12.3767            500001.0
502        704.0       241.0        10.9529            500001.0
506        742.0       242.0        11.8060            500001.0
531       1057.0       324.0        10.8111            500001.0
686       3011.0       993.0        10.7372            500001.0
710        549.0       190.0        10.7355            500001.0
747       1582.0       551.0        10.8980            500001.0
863       1176.0       351.0        10.3953            500001.0
894         37.0        27.0        10.2264            225000.0
997         59.0        21.0        11.7794            500001.0
1050        25.0         9.0        15.0001            350000.0
1080       345.0       129.0        10.0968            500001.0
1192       495.0       208.0        10.7097            500001.0
1222      2569.0       798.0        10.1570            477100.0
1263       836.0       337.0        12.8763            500001.0
1329      2528.0      1057.0        10.2233            500001.0
1383       100.0        47.0        15.0001            500001.0
1475      1024.0       370.0        15.0001            500001.0
1561       567.0       208.0        10.5793            500001.0
1600       749.0       260.0        15.0001            500001.0
1865       658.0       244.0        10.0825            397000.0
1880       705.0       186.0        10.3798            500001.0
1954      1315.0       582.0        11.5706            500001.0
2004      2768.0      1106.0        11.1978            500001.0
2050       641.0       251.0        10.0549            500001.0
2053       927.0       369.0        10.2811            500001.0
2199       798.0       243.0        15.0001            500001.0
2243      1608.0       561.0        10.7958            500001.0
2350      3599.0      1257.0        10.2292            500001.0
2384       531.0       161.0        15.0001            500001.0
2556       850.0       318.0        14.2867            500001.0
2583       809.0       291.0        15.0001            500001.0
      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
185     -118.28     34.02                29.0        515.0           229.0
2640    -114.62     33.62                26.0         18.0             3.0
2879    -121.84     38.02                46.0         66.0            22.0
641     -121.04     37.67                16.0         19.0            19.0
2841    -118.27     33.96                38.0       1126.0           270.0
...         ...       ...                 ...          ...             ...
2583    -118.41     34.09                37.0       2716.0           302.0
42      -118.06     34.15                37.0       1980.0           226.0
2199    -118.20     34.19                38.0       2176.0           266.0
1383    -118.37     34.10                37.0        407.0            67.0
161     -117.85     33.62                13.0       5192.0           658.0

      population  households  median_income  median_house_value
185       2690.0       217.0         0.4999            500001.0
2640         5.0         3.0         0.5360            275000.0
2879        37.0        21.0         0.5360             87500.0
641        166.0         9.0         0.5360            162500.0
2841       999.0       265.0         0.5495             91700.0
...          ...         ...            ...                 ...
2583       809.0       291.0        15.0001            500001.0
42         697.0       226.0        15.0001            500001.0
2199       798.0       243.0        15.0001            500001.0
1383       100.0        47.0        15.0001            500001.0
161       1865.0       662.0        15.0001            500001.0

[3000 rows x 9 columns]
                longitude   latitude  housing_median_age  total_rooms  \
median_income
0.4999        -118.280000  34.020000           29.000000   515.000000
0.5360        -119.166667  36.436667           29.333333    34.333333
0.5495        -118.270000  33.960000           38.000000  1126.000000
0.7054        -117.080000  33.120000           43.000000   107.000000
0.7403        -122.370000  37.960000           37.000000  1572.000000
...                   ...        ...                 ...          ...
12.6417       -122.340000  37.560000           39.000000  3562.000000
12.8763       -118.280000  34.120000           50.000000  2384.000000
13.6623       -117.180000  33.020000           15.000000  3540.000000
14.2867       -118.460000  34.070000           49.000000  2418.000000
15.0001       -118.633333  34.464444           33.666667  2215.444444

               total_bedrooms   population  households  median_house_value
median_income
0.4999             229.000000  2690.000000  217.000000       500001.000000
0.5360              14.666667    69.333333   11.000000       175000.000000
0.5495             270.000000   999.000000  265.000000        91700.000000
0.7054              44.000000   107.000000   48.000000       137500.000000
0.7403             402.000000  1046.000000  350.000000        68600.000000
...                       ...          ...         ...                 ...
12.6417            391.000000  1139.000000  391.000000       500001.000000
12.8763            312.000000   836.000000  337.000000       500001.000000
13.6623            453.000000  1364.000000  425.000000       500001.000000
14.2867            301.000000   850.000000  318.000000       500001.000000
15.0001            264.222222   733.111111  252.111111       483334.222222

[2578 rows x 8 columns]